import { useState, useRef, useCallback, type KeyboardEvent } from "react";
import { Send, Square } from "lucide-react";

interface ChatInputProps {
  onSend: (message: string) => void;
  onStop: () => void;
  isLoading: boolean;
}

export function ChatInput({ onSend, onStop, isLoading }: ChatInputProps) {
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmit = useCallback(() => {
    const trimmed = input.trim();
    if (!trimmed || isLoading) return;
    onSend(trimmed);
    setInput("");
    if (inputRef.current) {
      inputRef.current.style.height = "auto";
    }
  }, [input, isLoading, onSend]);

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleInput = useCallback(() => {
    const el = inputRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 160)}px`;
  }, []);

  return (
    <div className="border-t border-surface-800 bg-surface-900/80 backdrop-blur-xl">
      <div className="max-w-4xl mx-auto px-4 py-3 sm:py-4">
        <div className="flex items-end gap-2 bg-surface-800 rounded-2xl border border-surface-700/50
          focus-within:border-primary-500/50 focus-within:ring-1 focus-within:ring-primary-500/30
          transition-all duration-200 px-3 py-2">
          <textarea
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            onInput={handleInput}
            placeholder="Type your message..."
            rows={1}
            className="flex-1 bg-transparent text-sm text-gray-200 placeholder-gray-500
              resize-none outline-none max-h-40 py-1.5 px-1 scrollbar-thin"
            aria-label="Message input"
            disabled={isLoading}
          />
          {isLoading ? (
            <button
              onClick={onStop}
              className="shrink-0 w-9 h-9 rounded-xl bg-red-600 hover:bg-red-700
                flex items-center justify-center transition-colors duration-200
                focus:outline-none focus:ring-2 focus:ring-red-500/50"
              aria-label="Stop generation"
            >
              <Square className="w-4 h-4 text-white fill-white" aria-hidden="true" />
            </button>
          ) : (
            <button
              onClick={handleSubmit}
              disabled={!input.trim()}
              className="shrink-0 w-9 h-9 rounded-xl bg-primary-600 hover:bg-primary-700
                disabled:bg-surface-700 disabled:cursor-not-allowed
                flex items-center justify-center transition-all duration-200
                focus:outline-none focus:ring-2 focus:ring-primary-500/50
                active:scale-95"
              aria-label="Send message"
            >
              <Send className="w-4 h-4 text-white" aria-hidden="true" />
            </button>
          )}
        </div>
        <p className="text-[10px] text-gray-600 text-center mt-2">
          AI responses are generated by Groq. Verify important information.
        </p>
      </div>
    </div>
  );
}
